///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest195
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest195Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9a0859e8-a9e4-471f-a110-b20ccf76633a")]
    public partial class MyTest195Repository : RepoGenBaseFolder
    {
        static MyTest195Repository instance = new MyTest195Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest195Repository element repository.
        /// </summary>
        [RepositoryFolder("9a0859e8-a9e4-471f-a110-b20ccf76633a")]
        public static MyTest195Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest195Repository() 
            : base("MyTest195Repository", "/", null, 0, false, "9a0859e8-a9e4-471f-a110-b20ccf76633a", ".\\RepositoryImages\\MyTest195Repository9a0859e8.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9a0859e8-a9e4-471f-a110-b20ccf76633a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest195RepositoryFolders
    {
    }
#pragma warning restore 0436
}
